#! /usr/bin/env python

from cosmoslik_waf.utils import build_f2py, config_f2py, opt_f2py

def options(opt):
    opt_f2py(opt)
    
def configure(conf):
    config_f2py(conf)
    
def build(bld):
    build_f2py(bld,
               source='f_hubble_theta.f90', 
               module_name='f_hubble_theta',
               extra_sources='hubble_theta_convert.f90')
