#! /usr/bin/env python

from cosmoslik_waf.utils import build_f2py, opt_f2py, config_f2py, fpreproc
from cosmoslik_waf.wscript import check_lapack_blas, check_cfitsio

def options(opt):
    opt_f2py(opt)

def configure(conf):
    config_f2py(conf)
    check_lapack_blas(conf)
    check_cfitsio(conf)

def build(bld):
    wmapfiles = fpreproc(bld,bld.path.ant_glob('wmap_likelihood_v5/*90'))
    build_f2py(bld,
               source='pywmap.f90',
               module_name='pywmap',
               extra_sources=wmapfiles,
               includes=bld.path.find_node('wmap_likelihood_v5'),
               use='LAPACK CFITSIO')
