from cosmoslik.waftools import build_f2py, opt_f2py, config_f2py, fpreproc

def options(opt):
    opt_f2py(opt)

def configure(conf):
    config_f2py(conf)
    conf.env.INCLUDES = ['wmap']
    
def build(bld):
    wmapfiles = fpreproc(bld,bld.path.ant_glob('wmap/*90'))
    
    build_f2py(bld,
               source='pywmap.f90',
               module_name='pywmap',
               extra_sources=wmapfiles)
