#! /usr/bin/env python

import os.path as osp

def options(ctx):
    ctx.load('compiler_c python cython')

def configure(ctx):
    ctx.load('compiler_c python')
    ctx.check_python_headers()
    ctx.check_python_module('scipy','ver >= num(0,10)')
    ctx.load('cython')


def build(ctx):
    #hack since waf accidently thinks this cython file should produce a .h file  
    ctx(rule='touch ${TGT}', target='cosmo_derived.h')

    ctx(features = 'c cshlib pyext',
        source   = 'cosmo_derived.pyx',
        target   = 'cosmo_derived',
        install_path = osp.join('${PYTHONDIR}',ctx.path.path_from(ctx.root.find_node(ctx.top_dir))))
